### ISSUE TITLE
Error during build due to missing Test.Unit module.

### ISSUE THREAD

**Issue by epicallan** [nkly/purescript-express#66] opened 2017-04-14 07:22 UTC
```
Error found:
in module Node.Express.Test.Mock
Module Test.Unit was not found.

```

I downgraded to an earlier commit to get past this.

**Comment by anilanar** [comment] 2017-04-17 12:21
This is happening to due `Test.Mock` relying on `Test.Unit`. `Test.Unit` is a dev-dependency so it's not installed when you do `bower install`.

**Comment by epicallan** [comment] 2017-04-17 17:21
Thanks @anilanar.

**Comment by epicallan** [comment] 2017-05-11 17:16
Hi @anilanar is there special reason why `` Test.Unit `` was not included as dependency in the new updates or moving the Node.Express.Test.Mock module into the tests folders  since it breaks ``` pulp build ``` this can be a turn off for a new user.

If there is no special reason I could take a stub at refactoring the code.

**Comment by anilanar** [comment] 2017-05-11 21:37
There is no special reason.


On 11. May 2017 at 19:16:07, Lukwago Allan (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi @anilanar<https://github.com/anilanar> is there special reason why Test.Unit was not included as dependency in the new updates or moving the Node.Express.Test.Mock module into the tests folders since it breaks pulp build this can be a turn off for a new user.

If there is no special reason I could take a stub at refactoring the code.

**Comment by joaalto** [comment] 2017-05-15 10:58
Just tried to use the project and ran into this issue. I suppose this issue is caused by #64. Since the production code now depends on `Test.Unit`, shouldn't `purescript-test-unit` be moved from `devDependencies` to `dependencies`?

**Comment by joaalto** [comment] 2017-05-15 11:04
Ah, just noticed the fix is included here: #68.

**Comment by joaalto** [comment] 2017-05-31 19:17
Is it possible to get a new release now that this issue is fixed?

**Comment by nkly** [comment] 2017-06-01 09:56
@joaalto Sure. I was waiting for more PRs maybe being finished, but can also release now it it's necessary

**Closed** 2017-06-01 09:58 UTC
